# Generated by Django 4.0.5 on 2022-09-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
