# Generated by Django 4.0.5 on 2022-09-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_count_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='count',
            field=models.IntegerField(),
        ),
    ]
