# Generated by Django 4.0.5 on 2022-09-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
    ]
