# Generated by Django 4.0.5 on 2022-09-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_info',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
